# postgresql docker compose
version: '3.9'

services:
  postgres: 
    image: postgres:17.2
    container_name: postgres
    shm_size: 256mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: flip
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flipdns
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
